basePath: /
definitions:
  model.HealthResponse:
    properties:
      instance_id:
        example: "1234567890"
        type: string
      message:
        example: ok
        type: string
      service_name:
        example: golang-backend-ebvn-k04-day-1
        type: string
    type: object
info:
  contact: {}
  description: Health check API for Golang Backend EBVN K04 Day 1 assignment
  title: Golang Backend Health
  version: 1.0.0
paths:
  /health:
    get:
      description: Health check API for Golang Backend EBVN K04 Day 1 assignment
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.HealthResponse'
      summary: Health check
      tags:
      - health
swagger: "2.0"
